// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4cK0TSQXSW0jcjz2wKgcltwGxyRQX7So',
    appId: '1:972912647909:web:aaf33a67137a73ec623e0c',
    messagingSenderId: '972912647909',
    projectId: 'auctionapp-87bee',
    authDomain: 'auctionapp-87bee.firebaseapp.com',
    storageBucket: 'auctionapp-87bee.firebasestorage.app',
    measurementId: 'G-RB1C3CGWL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATn1hSKwv3DJOVqaQh0XUXlIsswa1eYWs',
    appId: '1:972912647909:android:9048d35f5d4b5574623e0c',
    messagingSenderId: '972912647909',
    projectId: 'auctionapp-87bee',
    storageBucket: 'auctionapp-87bee.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4cK0TSQXSW0jcjz2wKgcltwGxyRQX7So',
    appId: '1:972912647909:web:3f595d6c25907b87623e0c',
    messagingSenderId: '972912647909',
    projectId: 'auctionapp-87bee',
    authDomain: 'auctionapp-87bee.firebaseapp.com',
    storageBucket: 'auctionapp-87bee.firebasestorage.app',
    measurementId: 'G-839YFHT026',
  );
}
